python run_parallel.py \
    --group_name simba_rr1 \
    --exp_name simba_rr1 \
    --agent_config simba \
    --env_type mujoco \
    --device_ids 0 1 2 3 \
    --num_seeds 5 \
    --num_exp_per_device 5 \
    --server kaist \
    --overrides project_name='Simba_2501' \
    --overrides updates_per_interaction_step=0.5 \