python run_parallel_3000.py \
    --group_name hypersimba_hb_scaling \
    --exp_name hypersimba_critic_width_1024 \
    --agent_config hyper_simba_dev \
    --env_type mini_benchmark \
    --device_ids 0 1 2 3 \
    --num_seeds 1 \
    --num_exp_per_device 4 \
    --server kaist \
    --overrides project_name='Simba_2501' \
    --overrides updates_per_interaction_step=2 \
    --overrides agent.critic_hidden_dim=1024 \