##################################################################################
# Mujoco
##################################################################################

env_type: 'mujoco'
env_name: 'Humanoid-v4'
num_env_steps: 1_000_000
episodic: true

seed: ${seed}
num_train_envs: 1
num_eval_envs: 1
no_termination: false
action_repeat: 1
rescale_action: true
reward_scale: 1
max_episode_steps: 1000