##################################################################################
# MyoSuite
##################################################################################

env_type: 'myosuite'
env_name: 'myo-reach'
num_env_steps: 1_000_000
episodic: false

seed: ${seed}
num_train_envs: 1
num_eval_envs: 1
no_termination: false
action_repeat: 2
rescale_action: true
max_episode_steps: 100